### ISSUE TITLE
Bump package tar

### ISSUE THREAD

**Issue by prashant93** [signalfx/signalfx-nodejs-collect#14]
Team can you please update the tar package to latest tar has vulenrability in version 4.4.8

**Comment by prashant93** [comment]
I think PR is already raised

**Comment by owais** [comment]
Merged

**Comment by prashant93** [comment]
Thanks @owais

**Comment by owais** [comment]
It is a transitive/indirect dependency and we don't mention it anywhere in our library so we don't have to release anything.
